const habilidadesPokemon = {
    "stench": "Hedor",
    "drizzle": "Llovizna",
    "speed-boost": "Impulso",
    "battle-armor": "Armadura batalla",
    "sturdy": "Robustez",
    "damp": "Humedad",
    "limber": "Flexibilidad",
    "sand-veil": "Velo arena",
    "static": "Electricidad estática",
    "volt-absorb": "Absorbe electricidad",
    "water-absorb": "Absorbe agua",
    "oblivious": "Despiste",
    "cloud-nine": "Aclimatación",
    "compound-eyes": "Ojo compuesto",
    "insomnia": "Insomnio",
    "color-change": "Cambio color",
    "immunity": "Inmunidad",
    "flash-fire": "Absorbe fuego",
    "shield-dust": "Polvo escudo",
    "own-tempo": "",
    "suction-cups": "",
    "intimidate": "",
    "shadow-tag": "",
    "rough-skin": "",
    "wonder-guard": "",
    "levitate": "",
    "effect-spore": "",
    "synchronize": "",
    "clear-body": "",
    "natural-cure": "",
    "lightning-rod": "",
    "serene-grace": "",
    "swift-swim": "",
    "chlorophyll": "",
    "illuminate": "",
    "trace": "",
    "huge-power": "",
    "poison-point": "",
    "inner-focus": "",
    "magma-armor": "",
    "water-veil": "",
    "magnet-pull": "",
    "soundproof": "",
    "rain-dish": "",
    "sand-stream": "Chorro arena",
    "pressure": "Presión",
    "insomnia": "Insomnio",
}

export default habilidadesPokemon;